#!/bin/bash

chmod -R 755 /var/jb/Applications/VcamController.app 2>/dev/null || true

if [ -x /var/jb/usr/bin/uicache ]; then
    /var/jb/usr/bin/uicache -p /var/jb/Applications/VcamController.app 2>/dev/null || true
elif [ -x /usr/bin/uicache ]; then
    /usr/bin/uicache -p /var/jb/Applications/VcamController.app 2>/dev/null || true
fi

exit 0
